import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/styled-component";
import "bootstrap/dist/css/bootstrap.min.css";
import dynamic from "next/dynamic";
import ReactQuery from "@/lib/react-query";
import ReduxProvider from "@/lib/redux";
import Layout from "@/components/Layout";
const DynamicBootstrap = dynamic(
  () => require("bootstrap/dist/js/bootstrap.min.js"),
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MERN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ReduxProvider>
            <Layout>
              <ReactQuery>{children}</ReactQuery>
            </Layout>
          </ReduxProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
